version: '2'

services:
  samba:
    image: dperson/samba
    container_name: samba
    stdin_open: true
    tty: true
    environment:
      SHARE: 'PublishBuilds;/PublishBuilds;yes;no;yes;'
    volumes:
      - /PublishBuilds:/PublishBuilds 
      - default
    ports:
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
  restart: always
