version: '2'

services:

  sonarqube:
    image: sonarqube:9.4-community
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - sonar.es.bootstrap.checks.disable=true
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=PASSWORD
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-postgres:5432/sonar
    volumes:
      - sonar_datax:/opt/sonarqube/data:rw
      - sonar_conf:/opt/sonarqube/conf:rw
      - sonar_logs:/opt/sonarqube/logs:rw
      - sonar_ext:/opt/sonarqube/extensions:rw
    ports:
      - "9000:9000"
    networks:
      - sonarnet
#Добавление в хостс
    extra_hosts:
      - "DOMAIN:IP"
    restart: always

  sonarqube-postgres:
    image: postgres:11.15
    container_name: sonarqube-postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - sonar_data_db:/var/lib/postgresql/data:rw
    networks:
      - sonarnet
    restart: always

networks:
  sonarnet:
    driver: bridge
volumes:
  sonar_datax:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/storage/sonarqube/data/data/'
  sonar_conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/storage/sonarqube/data/conf/'
  sonar_logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/storage/sonarqube/data/logs/'
  sonar_ext:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/storage/sonarqube/data/extensions/'
  sonar_data_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/storage/sonarqube/db/'